version: '3.2'

services:
  frontend:
    image: nginx:1.15.2-alpine
    container_name: front
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/opt/device-health-front
    ports:
      - 80:80
    networks:
      - device_health_net

  backend:
    container_name: back
    depends_on:
      - postgres
    build:
      context: "./server"
      dockerfile: Dockerfile
    # ports:
      # - 8081:8080
    volumes:
      - type: bind
        source: ./server/target/
        target: /usr/local/tomcat/webapps/
      - type: bind
        source: ./server/target/
        target: /usr/local/tomcat/logs/
    networks:
      - device_health_net
 
  migrate:
    container_name: migrate
    depends_on:
      - postgres 
    
    build:
      context: "./migrate"
      dockerfile: Dockerfile
      args:
        -up: up
    volumes:
      - ./database/:/migrate/
      - ./migrate/migrate.sh:/opt/migrate.sh
    networks:
      - device_health_net
    environment:
      - DB_PORT_5432_TCP_ADDR=db
      - DB_PORT_5432_TCP_PORT=5432
      - DB_ENV_POSTGRES_SCHEMA=device_health_development
      - DB_ENV_POSTGRES_USER=postgres
      - DB_ENV_POSTGRES_PASSWORD=postgres

  postgres:
    container_name: db
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgres/data
      - POSTGRES_DB=device_health_development
    volumes:
      - type: bind
        source: dbdata
        target: /var/lib/postgres/data
      - ./database/misc_scripts/:/docker-entrypoint-initdb.d/
    networks:
      - device_health_net
    

networks:
  device_health_net:

volumes:
  dbdata: